### ISSUE TITLE
undefined local variable or method `metadata', incompatible with mongoid-observers

### ISSUE THREAD

**Issue by zeitnot** [aq1018/mongoid-history#121]
Hi,
I got <a href='https://gist.github.com/zeitnot/31c507f0a6a4714a9d11'>this</a> error. I do not know why. What is the proper way to install this gem.

**Comment by sivagollapalli** [comment]
@dblock I think this Issue has been fixed. I just run all specs with `mongoid-observers` in `Gemfile`. All test cases have been passed. Would be better if we include `mongoid-observers` in `Gemfile` such that if any incompatibility arises we can catch easily. Thoughts, please?

**Comment by dblock** [comment]
I'd appreciate a PR with mongoid-observers running part of the build, thanks!

**Comment by dblock** [comment]
Closing via https://github.com/aq1018/mongoid-history/pull/160.
