### ISSUE TITLE
Query! Is thr any way to go back association_chain obj from HistoryTracker object

### ISSUE THREAD

**Issue by sahilchopra** [aq1018/mongoid-history#147]
Hi

my histroy tracker object is

`#<HistoryTracker _id: 56dedd17b0386e38a81e5521, created_at: 2016-03-08 14:09:27 UTC, updated_at: 2016-03-08 14:09:27 UTC, association_chain: [{"name"=>"Person", "id"=>BSON::ObjectId('56dd1017b0386e18466de03c')}], modified: {"first_name"=>"sahil"}, original: {"first_name"=>"test2"}, version: 3, action: "update", scope: "person", modifier_id: nil>`

i want to go back to Person(BSON::ObjectId('56dd1017b0386e18466de03c')) object from history_tracker object.
Is thr any way this Gem provide.

Thanks

**Comment by dblock** [comment]
I think you're looking for `.trackable`. Note that for embedded objects that might be `trackable_root`. See https://github.com/aq1018/mongoid-history/blob/master/lib/mongoid/history/tracker.rb#L68. Reopen if that's not what you're looking for. Also would appreciate a PR that improves the documentation!
